spring.application.name=tech-paranoia-server
spring.datasource.url=jdbc:postgresql://localhost:5432/tech-paranoia-db
spring.datasource.username=postgres
spring.datasource.password=jack
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

server.port=8081

application.jwt.secret-key=1oui239dh1u909mh4r09h2039u4hr09fu2mh3rt9h09fgmhpfugjh
application.jwt.expiration=1840000
